# Generated by Django 4.2.6 on 2023-10-09 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile/%Y/%m/')),
                ('introduce_me', models.TextField()),
                ('name', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('job', models.CharField(max_length=50)),
                ('religion', models.CharField(choices=[('개신교', 'Protestantism'), ('불교', 'Buddhism'), ('천주교', 'Catholicism'), ('기타', 'Others'), ('종교 없음', 'No Religion')], max_length=10)),
                ('my_character', models.TextField()),
                ('purpose_to_join', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
