# Generated by Django 4.2.6 on 2023-10-11 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like',
            field=models.ManyToManyField(related_name='like_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
